### ISSUE TITLE
Console showing options

### ISSUE THREAD

**Issue by slushman** [PavelDemyanenko/gulp-parker#12]
Line 48 has the gulp-parker options being printed to the console, but this ends up being inline with the reports. Could that be commented out or at least optional?

<img width="465" alt="screenshot 2016-11-15 15 12 56" src="https://cloud.githubusercontent.com/assets/2255645/20324390/07506186-ab46-11e6-8a6d-4fd06720f4fd.png">

**Comment by PavelDemyanenko** [comment]
@slushman sure, I'll check it, thnx for feedback :+1:

**Comment by PavelDemyanenko** [comment]
Fixed in new version
