### ISSUE TITLE
Don't output full file path?

### ISSUE THREAD

**Issue by mdo** [PavelDemyanenko/gulp-parker#3]
I'm working on moving a project from Grunt to Gulp and ran into a small nit: the file path headings include the full `pwd` in the output Markdown file. Could we keep the file paths local to the project instead?

For example, can you do:

```
### css/primer.css
```

...instead of:

```
### /Users/mdo/work/primer/css/primer.css
```

<3

**Comment by PavelDemyanenko** [comment]
@mdo I'll do it! thanks :+1:
